import { Geist, Geist_Mono } from "next/font/google";
import AnimatedCursor from "@/components/AnimatedCursor";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  preload: false,
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  preload: false,
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col relative">
        <AnimatedCursor />
        <header className="fixed top-0 left-0 w-full p-8 md:p-12 lg:px-16 z-50 pointer-events-none flex justify-between items-start">
          <Link href="/" className="pointer-events-auto flex flex-col items-center">
            <Image src="/images/Logo.png" alt="Lynx Logo" width={400} height={160} className="w-auto h-32 md:h-48" unoptimized priority />
          </Link>
        </header>
        {children}
      </body>
    </html>
  );
}
